name: FK_Balance
version: '1.0-SNAPSHOT'
main: br.ufpb.dcx.lima.albiere.fK_Money.FK_Balance
api-version: '1.21.4'
commands:
  money:
    description: Comando de economia, use /money para ver seu saldo.